feat: popup notification
henefisa/xfs-chat-app-frontend pull request #100
Opened 2022-12-18 04:13 UTC by leeduy1

2022-12-18 05:33 UTC, vuidv54 commented on src/components/modules/Notification/Notification.tsx
> +import ListRequestFriend from '../ListRequestFriend/ListRequestFriend';
sửa path, move lên

2022-12-18 05:41 UTC, vuidv54 commented on src/pages/Dashboard/Dashboard.tsx
> +import Notification from '@modules/Notification/Notification';
move lên

2022-12-18 12:01 UTC, vuidv54 commented on src/components/modules/Notification/Notification.tsx
> +          className={clsx('btn-all', active && 'btn-all--active')}
ai lại handle class kiểu này, clsx('btn-all', {['btn-all--active']: active})

2022-12-18 12:01 UTC, vuidv54 commented on src/components/modules/Notification/Notification.tsx
> +          className={clsx('btn-unread', !active && 'btn-unread--active')}
tương tự trên

2022-12-18 12:01 UTC, vuidv54 commented on src/components/modules/Notification/Notification.tsx
> +          onClick={React.useCallback(() => setActive(false), [active])}
viết ra function

2022-12-20 02:31 UTC, henefisa requested changes

2022-12-20 02:31 UTC, henefisa commented on src/components/modules/NavDashboard/NavDashboard.tsx
> +
vì sao khi click lại update notification

2022-12-25 12:09 UTC, henefisa approved these changes

2022-12-26 02:59 UTC, henefisa approved these changes

2022-12-26 02:59 UTC, merged