feat: merge avatars in chat
henefisa/xfs-chat-app-frontend pull request #111
Opened 2023-02-05 06:29 UTC by leeduy1

2023-02-05 12:12 UTC, henefisa requested changes

2023-02-05 12:12 UTC, henefisa commented on src/components/modules/ChatMain/ChatMain.tsx
>    });
useEffect ko có deps à

2023-02-05 12:13 UTC, leeduy1 commented on src/components/modules/ChatMain/ChatMain.tsx
>    });
cái đó em không làm anh

2023-02-05 12:14 UTC, henefisa commented on src/components/modules/ChatMain/ChatMain.tsx
>    });
sửa đi

2023-02-06 12:04 UTC, henefisa requested changes

2023-02-06 12:04 UTC, henefisa commented on src/components/modules/ChatMain/ChatMain.tsx
> +  }, [listMessage]);
Update vầy bị loop rồi, đang update list message mà sao lại bỏ list message vô deps

2023-02-06 12:18 UTC, leeduy1 commented on src/components/modules/ChatMain/ChatMain.tsx
> +  }, [listMessage]);
Em test nó ko bị loop anh

2023-02-07 13:32 UTC, henefisa approved these changes

2023-02-07 13:32 UTC, merged