fix: change classname, event button
henefisa/xfs-chat-app-frontend pull request #23
Opened 2022-10-28 17:06 UTC by huy21it

Review e vs ạ

2022-10-29 04:28 UTC, henefisa requested changes

2022-10-30 17:01 UTC, henefisa requested changes

2022-10-31 05:28 UTC, vuidv54 reviewed
check...

2022-10-31 17:52 UTC, vuidv54 reviewed
Check

2022-10-31 18:39 UTC, vuidv54 reviewed
Checkk

2022-11-01 16:39 UTC, henefisa requested changes

2022-11-03 03:11 UTC, henefisa requested changes

2022-11-03 17:17 UTC, henefisa requested changes

2022-11-04 11:32 UTC, henefisa requested changes

2022-11-05 10:40 UTC, henefisa requested changes

2022-11-06 12:00 UTC, vuidv54 commented on src/components/common/Modal/Modal.tsx
> +interface IModalProps extends ModalProps {}
dùng props className mà chưa định nghĩa type

2022-11-06 13:25 UTC, henefisa requested changes

2022-11-06 13:25 UTC, henefisa commented on src/components/common/Modal/Modal.tsx
> +interface IModalProps extends ModalProps {}
trong interface của antd có sẵn r

2022-11-06 13:25 UTC, henefisa commented on src/components/modules/ForwardForm/ForwardForm.scss
> +    height: 380px;
đừng set height

2022-11-06 13:25 UTC, henefisa commented on src/components/modules/ForwardForm/ForwardForm.scss
> +          li {
class name đâu

2022-11-07 01:55 UTC, henefisa requested changes

2022-11-07 01:55 UTC, henefisa commented on src/components/modules/ForwardForm/ForwardForm.scss
> +            }
move ra cùng cấp với .contact-names__items

2022-11-07 01:55 UTC, henefisa commented on src/components/modules/ForwardForm/ForwardForm.scss
> +            }
tương tự với .contact-names__label

2022-11-07 15:10 UTC, henefisa approved these changes

2022-11-07 15:11 UTC, merged