Refactor/chatbox2
henefisa/xfs-chat-app-frontend pull request #40
Opened 2022-11-13 15:38 UTC by huy21it

2022-11-13 16:50 UTC, vuidv54 commented on src/components/modules/ChatBottom/ChatBottom.tsx
> +import Dropdown from 'src/components/common/Dropdown/Dropdown';
sửa path

2022-11-13 17:01 UTC, vuidv54 commented on src/components/modules/ChatBottom/ChatBottom.tsx
> +  Messages: React.Dispatch<React.SetStateAction<string[]>>;
ủa gì đây

2022-11-13 17:03 UTC, henefisa requested changes

2022-11-13 17:03 UTC, henefisa commented on src/components/modules/ChatUI/ChatUI.tsx
> +  const [mess, setMess] = useState(['']);
dat ten phai ro~ rang

2022-11-13 17:03 UTC, henefisa commented on src/components/modules/MessagesTable/MessagesTable.tsx
> +  Messages: string;
vi sao lai viet hoa

2022-11-14 04:50 UTC, vuidv54 commented on package.json
> +    "react-use-draggable-scroll": "^0.4.7",
remove

2022-11-15 03:38 UTC, henefisa approved these changes

2022-11-15 03:38 UTC, merged