feat: update profile
henefisa/xfs-chat-app-frontend pull request #71
Opened 2022-11-24 13:48 UTC by leeduy1

2022-11-24 14:00 UTC, vuidv54 commented on src/pages/Dashboard/Dashboard.tsx
> +import ENavbar from 'src/interfaces/ENavbar';
move lên

2022-11-24 14:01 UTC, vuidv54 commented on src/services/userService.ts
> +
lấy type trong models/user

2022-11-24 14:05 UTC, vuidv54 commented on src/services/userService.ts
> +    dispatch(getProfileFailed());
updateProfileFailed chứ

2022-11-24 14:06 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.scss
> +    .avatar-settings--inner {
__inner

2022-11-24 14:07 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.scss
> +    .ant-typography + h5.ant-typography {
đặt lên class mà css

2022-11-24 14:08 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.scss
> +    .account-details--inner {
__inner

2022-11-24 14:09 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.scss
> +          .cancel-button {
form-button__cancel

2022-11-24 14:10 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.scss
> +          .save-change-button {
form-button__save-change

2022-11-24 14:11 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.scss
> +        .panel-inner {
security__inner

2022-11-24 14:12 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.scss
> +        .panel-inner {
security__panel

2022-11-24 14:12 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.scss
> +          .security-item {
panel-item

2022-11-24 14:13 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.scss
> +          }
convention

2022-11-24 14:13 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +import { Divider } from 'antd';
lấy ở common

2022-11-24 14:14 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +    console.log(values);
xóa console.log

2022-11-24 14:34 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +import TextArea from 'antd/lib/input/TextArea';
?

2022-11-24 14:35 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +  );
bỏ đi

2022-11-24 14:35 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +  };
bỏ luôn, ant có handle sẵn

2022-11-24 14:35 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +                  description: description,
lấy từ store

2022-11-24 14:35 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +                onValuesChange={onValuesChange}
bỏ

2022-11-25 10:00 UTC, henefisa requested changes

2022-11-25 10:00 UTC, henefisa commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +import TextArea from 'antd/lib/input/TextArea';
common component

2022-11-26 04:29 UTC, henefisa approved these changes

2022-11-26 04:29 UTC, henefisa commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +          {active === 3 && (
dung string thay vi dung number 
vd: active === ESidebarSetting.HELP

2022-11-26 04:29 UTC, henefisa commented on src/pages/Dashboard/Dashboard.tsx
> +      {navbarAction === ENavbar.SETTINGS ? (
good

2022-11-26 09:58 UTC, henefisa approved these changes

2022-11-26 09:59 UTC, merged