feat: check update profile
henefisa/xfs-chat-app-frontend pull request #82
Opened 2022-12-03 06:47 UTC by leeduy1

2022-12-03 10:16 UTC, vuidv54 commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +  const handleFormChange = (
handleValueChange

2022-12-03 16:07 UTC, henefisa requested changes

2022-12-03 16:07 UTC, henefisa commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +  const handleValueChage = (
sai chinh ta

2022-12-03 16:07 UTC, henefisa commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +    newInfoUser: TUserInfo
viet ra interfaces

2022-12-03 16:07 UTC, henefisa commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +  };
viet util de check

2022-12-05 02:39 UTC, henefisa requested changes

2022-12-05 02:39 UTC, henefisa commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +    }
refactor

2022-12-05 02:39 UTC, henefisa commented on src/models/user.ts
> +  location: null | string | undefined;
refactor

2022-12-05 02:39 UTC, henefisa commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +  const handleValueChange = (e: IChangeField, newInfoUser: TUserInfo) => {
handleValueChange -> handleValuesChange

2022-12-05 02:39 UTC, henefisa commented on src/utils/checkdisabled.ts
> +};
refactor

2022-12-05 02:39 UTC, henefisa commented on src/utils/checkdisabled.ts
> +
src/utils/checkdisabled.ts -> sai convention dat ten

2022-12-07 03:31 UTC, henefisa requested changes

2022-12-07 03:31 UTC, henefisa commented on src/components/modules/SidebarSettings/SidebarSettings.tsx
> +      const user = { ...values, avatar: res.key };
user -> profile

2022-12-07 03:31 UTC, henefisa commented on src/utils/compareObjects.ts
> +};
remove

2022-12-07 03:31 UTC, henefisa commented on src/utils/compareObjects.ts
> +};
compare thẳng trong handler

2022-12-07 07:09 UTC, henefisa approved these changes

2022-12-07 07:09 UTC, merged