feat: view messages
henefisa/xfs-chat-app-frontend pull request #83
Opened 2022-12-03 18:12 UTC by huy21it

2022-12-04 01:38 UTC, vuidv54 commented on src/components/common/Conversation/Conversation.tsx
> +import AvatarGroupChat from 'src/components/modules/AvatarGroupChat/AvatarGroupChat';
sửa path import

2022-12-04 01:40 UTC, vuidv54 commented on src/components/modules/ChatBottom/ChatBottom.tsx
>  const ChatBottom: React.FC<IChatBottom> = ({ setMessagesUser }) => {
bỏ setMessagesUser, ko cần thiết nữa

2022-12-04 01:40 UTC, vuidv54 commented on src/components/modules/ChatBottom/ChatBottom.tsx
> +    setMessagesUser((prev: string[]) => [...prev, messages]);
bỏ

2022-12-05 07:04 UTC, vuidv54 commented on src/components/modules/ChatBottom/ChatBottom.tsx
> +import { notification } from 'antd';
move lên

2022-12-05 07:05 UTC, vuidv54 commented on src/components/modules/ChatBottom/ChatBottom.tsx
> +      if (!hasConversation || selectedFriend) {
!hasConversation && selectedFriend

2022-12-05 07:05 UTC, vuidv54 commented on src/components/modules/ChatBottom/ChatBottom.tsx
> +            { members: [userProfileStore.id, selectedFriend?.id || ''] },
{ members: [userProfileStore.id, selectedFriend.id ] }

2022-12-05 07:05 UTC, vuidv54 commented on src/components/modules/ChatBottom/ChatBottom.tsx
> +          console.log(res);
delete

2022-12-05 07:06 UTC, vuidv54 commented on src/components/modules/ChatBottom/ChatBottom.tsx
> +          });
ko cần

2022-12-05 07:47 UTC, vuidv54 commented on src/components/modules/ChatBottom/ChatBottom.tsx
> +    if (!userProfileStore || !messages) return;
!message.trim()

2022-12-06 17:24 UTC, henefisa requested changes

2022-12-06 17:24 UTC, henefisa commented on src/components/modules/AvatarGroupChat/AvatarGroupChat.tsx
> +  imgwidth,
camelCase

2022-12-06 17:24 UTC, henefisa commented on src/components/modules/ChatBottom/ChatBottom.tsx
> +          }
remove

2022-12-07 03:23 UTC, henefisa requested changes

2022-12-07 03:23 UTC, henefisa commented on src/components/modules/ChatBottom/ChatBottom.tsx
> +  };
update

2022-12-07 03:23 UTC, henefisa commented on src/components/modules/ChatCall/ChatCall.tsx
> +import AvatarGroupChat from '../AvatarGroupChat/AvatarGroupChat';
import

2022-12-07 03:23 UTC, henefisa commented on src/utils/getTime.ts
> +export default getTime;
remove

2022-12-07 03:23 UTC, henefisa commented on src/utils/getMemberConversation.ts
> +};
đoạn này là sao

2022-12-07 03:23 UTC, henefisa commented on src/utils/getGroupTitle.ts
> +  );
newPariticipants là gì

2022-12-07 03:23 UTC, henefisa commented on src/store/userSlice.ts
> +    error: false,
Tách nhỏ cái slice ra

2022-12-07 03:23 UTC, henefisa commented on src/store/userSlice.ts
> +    },
Tách reducer ra 1 slice khác

2022-12-07 03:23 UTC, henefisa commented on src/services/userService.ts
> +
remove

2022-12-07 03:23 UTC, henefisa commented on src/pages/Dashboard/Dashboard.tsx
> +          }
remove this callback

2022-12-07 03:23 UTC, henefisa commented on src/pages/Dashboard/Dashboard.tsx
> +        const result = await getListConversation({}, t);
sao lại truyền empty object

2022-12-07 03:23 UTC, henefisa commented on src/pages/Dashboard/Dashboard.tsx
> +        dispatch(updateListConversation([]));
chưa handle errror

2022-12-07 03:23 UTC, henefisa commented on src/models/user.ts
> +  MEMBER = 'MEMBER',
remove

2022-12-07 03:23 UTC, henefisa commented on src/models/conversation.ts
> +  id: string;
vì sao id lại require

2022-12-07 03:23 UTC, henefisa commented on src/components/modules/UserInfoChat/UserInfoChat.tsx
> +    selectedFriend?.username;
refactor

2022-12-07 03:23 UTC, henefisa commented on src/components/modules/ChatMain/ChatMain.tsx
> +        );
refactor

2022-12-07 03:23 UTC, henefisa commented on src/components/modules/ChatMain/ChatMain.tsx
> +      // do something
// do something ???

2022-12-07 03:23 UTC, henefisa commented on src/components/modules/ChatMain/ChatMain.tsx
> +          sender: user,
remove

2022-12-07 03:23 UTC, henefisa commented on src/components/modules/ChatHeader/ChatHeader.tsx
> +    getMemberConversation(selectedConversation, userProfileStore)?.username;
refactor

2022-12-07 03:23 UTC, henefisa commented on src/components/modules/ChatHeader/ChatHeader.tsx
> +        )}
refactor

2022-12-07 03:23 UTC, henefisa commented on src/components/modules/ChatHeader/ChatHeader.tsx
> +  const [hasConversation, setHasConversation] = React.useState<boolean>(false);
remove

2022-12-07 03:23 UTC, henefisa commented on src/components/modules/ChatHeader/ChatHeader.tsx
> +import AvatarGroupChat from '../AvatarGroupChat/AvatarGroupChat';
check import

2022-12-07 03:23 UTC, henefisa commented on src/components/modules/ChatCall/ChatCall.tsx
> +    selectedFriend?.username;
refactor

2022-12-07 03:23 UTC, henefisa commented on src/components/modules/ChatCall/ChatCall.tsx
> +          )}
refactor

2022-12-07 03:30 UTC, huy21it commented on src/utils/getMemberConversation.ts
> +};
trong 1 conversation chỉ có 2 người thì sẽ có 1 hàm check xem đâu làm mình a

2022-12-13 11:33 UTC, closed without merging